#include "HotDrone_AttEstimator_ekf.h"




HotDrone_AttEstimator_ekf::HotDrone_AttEstimator_ekf()
{

	_q0 = HOTDRONE_ATTESTIMATOR_EKF_Q0;
	_q1 = HOTDRONE_ATTESTIMATOR_EKF_Q1;
	_q2 = HOTDRONE_ATTESTIMATOR_EKF_Q2;
	_q3 = HOTDRONE_ATTESTIMATOR_EKF_Q3;
	_q4 = HOTDRONE_ATTESTIMATOR_EKF_Q4;

	_r0 = HOTDRONE_ATTESTIMATOR_EKF_R0;
	_r1 = HOTDRONE_ATTESTIMATOR_EKF_R1;
	_r2 = HOTDRONE_ATTESTIMATOR_EKF_R2;
	_r3 = HOTDRONE_ATTESTIMATOR_EKF_R3;

	_roll_off = HOTDRONE_ATTESTIMATOR_EKF_ROLL_OFF;
	_pitch_off = HOTDRONE_ATTESTIMATOR_EKF_PITCH_OFF;
	_yaw_off = HOTDRONE_ATTESTIMATOR_EKF_YAW_OFF;

}

HotDrone_AttEstimator_ekf::~HotDrone_AttEstimator_ekf()
{


}